# Generated by Django 4.1.2 on 2022-12-11 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_description_productcategories_descriptions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
